#ifndef COMMON_H
#define COMMON_H

/**
 * @file common.h
 * @brief Common utility functions and version information for the Obsidian compiler.
 *
 * This header file defines common utility functions used across the Obsidian 
 * compiler, including functions for displaying help menus, version information, 
 * and system information. It also defines version macros for the compiler.
 * 
 * @author Codezz-ops <codezz-ops@obsidian.cc>
 * 
 * @copyright Copyright (c) 2024 Obsidian Language
 * @license BSD 3-Clause
 */

#include <stddef.h>

#define MAJOR_VERSION 0
#define MINOR_VERSION 1
#define PATCH_VERSION 0

/**
 * @brief Prints the help menu for the Obsidian compiler.
 * 
 * This function displays a menu of available commands and options for 
 * using the Obsidian compiler.
 */
void printHelpMenu(void);

/**
 * @brief Prints the version information of the Obsidian compiler.
 * 
 * This function outputs the current version of the compiler to the console.
 */
void printVersion(void);

/**
 * @brief Prints help information for available optimizers.
 * 
 * This function displays information about the optimizers that can be 
 * used with the Obsidian compiler.
 */
void printOptimizersHelp(void);

/**
 * @brief Prints help information for target platforms.
 * 
 * This function displays information about the target platforms supported 
 * by the Obsidian compiler.
 */
void printTargetHelp(void);

/**
 * @brief Prints help information for warnings.
 * 
 * This function displays information about the warnings that can be 
 * generated by the Obsidian compiler.
 */
void printWarningsHelp(void);

/**
 * @brief Retrieves system information.
 * 
 * This function fills the provided output buffer with information about 
 * the system, such as OS version and architecture.
 * 
 * @param output Pointer to the buffer where the system information will be stored.
 * @param size Size of the output buffer.
 */
void systemInfo(char *output, size_t size);

#endif // COMMON_H
