name: Update Blog from ChangeLog

on:
  push:
    branches:
      - master
    paths:
      - 'ChangeLog'

jobs:
  update-blog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout obsidian-c repo
        uses: actions/checkout@v3
        with:
          repository: obsidian-language/obsidian-c

      - name: Extract latest ChangeLog entry
        id: changelog
        run: |
          echo "Extracting latest ChangeLog entry..."
          NEW_ENTRY=$(awk '/^## /{if (p) exit; p=1} p' ChangeLog)
          echo "$NEW_ENTRY" > latest_entry.txt
          TITLE=$(echo "$NEW_ENTRY" | head -n 1 | sed 's/^## //')
          DATE=$(date +'%Y-%m-%d')
          FILENAME="_posts/${DATE}-${TITLE// /-}.md"
          echo "title=$TITLE" >> $GITHUB_ENV
          echo "filename=$FILENAME" >> $GITHUB_ENV

      - name: Checkout obsidian.github.io repo
        uses: actions/checkout@v3
        with:
          repository: obsidian-language/obsidian.github.io
          path: obsidian.github.io
          token: ${{ secrets.GH_PAT }}

      - name: Create a new Jekyll post
        run: |
          cd obsidian.github.io
          mkdir -p _posts
          echo "---" > ${{ env.filename }}
          echo "title: \"${{ env.title }}\"" >> ${{ env.filename }}
          echo "date: $(date -I)" >> ${{ env.filename }}
          echo "layout: default" >> ${{ env.filename }}
          echo "---" >> ${{ env.filename }}
          cat ../latest_entry.txt >> ${{ env.filename }}
          
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"
          git add ${{ env.filename }}
          git commit -m "New post from ChangeLog: ${{ env.title }}"
          git push origin main
