name: CI

on:
  push:
    branches:
      - master
      - generation
  pull_request:
    branches:
      - master
      - generation

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up dependencies (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y flex bison gcc python3-pip

    - name: Set up dependencies (Mac)
      if: runner.os == 'macOS'
      run: |
        brew update
        brew install gcc flex bison python

    - name: Set up MSYS2 and dependencies (Windows)
      if: runner.os == 'Windows'
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        install: >-
          base-devel
          flex
          bison
          python
          mingw-w64-x86_64-gcc
        update: true

    - name: Bootstrap the build system (Linux)
      if: runner.os == 'Linux'
      run: |
        pip install -r requirements.txt
        ./boot

    - name: Bootstrap the build system (Mac)
      if: runner.os == 'macOS'
      run: |
        pip3 install -r requirements.txt --break-system-packages
        ./boot

    - name: Bootstrap the build system (Windows)
      if: runner.os == 'Windows'
      shell: msys2 {0}
      run: |
        pip install -r requirements.txt --break-system-packages

    - name: Build the project (Linux)
      if: runner.os == 'Linux'
      run: |
        ./boot

    - name: Build the project (Mac)
      if: runner.os == 'macOS'
      run: |
        ./boot --cc-flags=-std=c11

    - name: Build the project (Windows)
      if: runner.os == 'Windows'
      shell: msys2 {0}
      run: |
         ./boot