name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up dependencies (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y autoconf automake libtool make gcc

    - name: Set up dependencies (Mac)
      if: runner.os == 'macOS'
      run: |
        brew update
        brew install gcc autoconf automake python

    - name: Set up MSYS2 and dependencies (Windows)
      if: runner.os == 'Windows'
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        install: >-
          base-devel
          autotools
          libtool
          make
          python
          mingw-w64-x86_64-gcc
        update: true

    - name: Bootstrap the build system
      run: ./boot

    - name: Configure the project
      run: ./configure

    - name: Build the project
      run: make

  build-x86_64:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y autoconf automake libtool make gcc

    - name: Build project
      run: |
        ./boot
        ./configure
        make check

  build-aarch64:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run on aarch64
      uses: uraimo/run-on-arch-action@v2
      with:
        arch: aarch64
        distro: ubuntu_latest
        install: |
          apt-get update
          apt-get install -y autoconf automake libtool make gcc python

        run: |
          ./boot
          ./configure
          make check

  build-armv7:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run on armv7
      uses: uraimo/run-on-arch-action@v2
      with:
        arch: armv7
        distro: bookworm
        install: |
          apt-get update
          apt-get install -y autoconf automake libtool make gcc python

        run: |
          ./boot
          ./configure
          make check

  build-armv6:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run on armv6
      uses: uraimo/run-on-arch-action@v2
      with:
        arch: armv6
        distro: bookworm
        install: |
          apt-get update
          apt-get install -y autoconf automake libtool make gcc python

        run: |
          ./boot
          ./configure
          make check

  build-riscv64:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run on riscv64
      uses: uraimo/run-on-arch-action@v2
      with:
        arch: riscv64
        distro: bookworm
        install: |
          apt-get update
          apt-get install -y autoconf automake libtool make gcc python

        run: |
          ./boot
          ./configure
          make check

  build-ppc64le:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run on ppc64le
      uses: uraimo/run-on-arch-action@v2
      with:
        arch: ppc64le
        distro: bookworm
        install: |
          apt-get update
          apt-get install -y autoconf automake libtool make gcc python

        run: |
          ./boot
          ./configure
          make check

  build-s390x:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run on s390x
      uses: uraimo/run-on-arch-action@v2
      with:
        arch: s390x
        distro: bookworm
        install: |
          apt-get update
          apt-get install -y autoconf automake libtool make gcc python

        run: |
          ./boot
          ./configure
          make check
