name: CI

on:
  push:
    branches:
      - master
      - generation
  pull_request:
    branches:
      - master
      - generation

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up dependencies
      run: |
        if [ $RUNNER_OS == 'Linux' ]; then
          sudo apt-get update
          sudo apt-get install -y flex bison gcc meson
        elif [ $RUNNER_OS == 'macOS' ]; then
          brew update
          brew install gcc flex bison meson
        elif [ $RUNNER_OS == 'Windows' ]; then
          msys2_setup -y base-devel flex bison meson mingw-w64-x86_64-gcc
        fi

    - name: Bootstrap the build system
      run: |
        meson setup build

    - name: Build the project
      run: |
        meson compile -C build