name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up dependencies
      run: |
        if [ ${{ runner.os }} == 'Linux' ]; then
          sudo apt-get update
          sudo apt-get install -y autoconf automake libtool make gcc
        fi
        
    - name: Bootstrap the build system
      run: |
        ./boot

    - name: Configure the project
      run: |
        ./configure

    - name: Build the project
      run: |
        make