name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up dependencies (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y autoconf automake libtool make gcc

    - name: Set up MSYS2 and dependencies (Windows)
      if: runner.os == 'Windows'
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        install: >-
          base-devel
          autotools
          libtool
          make
        update: true

    - name: Bootstrap the build system
      shell: msys2 {0}
      run: |
        ./boot

    - name: Configure the project
      shell: msys2 {0}
      run: |
        ./configure

    - name: Build the project
      shell: msys2 {0}
      run: |
        make
